name       : libgoffice
version    : 0.10.34
release    : 6
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/goffice/0.10/goffice-0.10.34.tar.xz : 554a75a22b5863b3b17595148bee6462122f2dbf031dfa78b61e941e3c2dd603
license    : GPL-2.0
component  : office
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(libxslt)
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
