name        : libgoffice
version     : 0.10.27
release     : 4
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/goffice/0.10/goffice-0.10.27.tar.xz : 3717b400fd190f18cf1dd7a16e1991b1f7c7cbdfeb1993656e7972347168d8c0
license     : GPL-2.0+
summary     : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps   :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libgsf-1)
description : |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
clang       : no
setup       : |
    %configure
build       : |
    %make
install     : |
    %make_install
