name       : libgoffice
version    : 0.10.37
release    : 9
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.37.tar.xz : 51b4e05dbfca5566409a7461e03b08b8882ba5f5e1b322de19eea05009700fe1
license    : GPL-2.0
component  : office
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
