name       : libgoffice
version    : 0.10.35
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/goffice/0.10/goffice-0.10.35.tar.xz : c19001afca09dc5446e06605a113d81a57124018a09c5889aeebba16cf1d5738
license    : GPL-2.0
component  : office
summary    : The GOffice package contains a library of GLib/GTK document centric objects
    and utilities.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
