name       : libgoffice
version    : 1.10.51
release    : 23
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.51.tar.xz : 2e8410884d6a51ae00c9420928abfa73f7a552c1aa222371df4f2dc5acc3cd23
license    : GPL-2.0-or-later
component  : programming.library
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
