name        : libgoffice
version     : 0.10.22
release     : 3
source      :
    - http://ftp.gnome.org/pub/gnome/sources/goffice/0.10/goffice-0.10.22.tar.xz : 0206a87a323b52a874dc54491374245f9e1c5f62e93a2ce4a02fb444a26b0e28
license     : GPL-2.0+
summary     : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps   :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libgsf-1)
description : |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
clang       : no
setup       : |
    %configure
build       : |
    %make
install     : |
    %make_install
