name       : libgoffice
version    : 0.10.41
release    : 12
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.41.tar.xz : 0cf7335914be0c7e96205d3e8b03dbc619995a7a3b41c3b675ef6b3a54a888b6
license    : GPL-2.0-or-later
component  : office
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
