name       : libgoffice
version    : 0.10.44
release    : 15
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.44.tar.xz : 6d6042af92cd962604068dbced5925948af6c812c2138defc3153c204d65a7b9
license    : GPL-2.0-or-later
component  : programming.library
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
