name        : libgoffice
version     : 0.10.28
release     : 5
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/goffice/0.10/goffice-0.10.28.tar.xz : 068f060de1a4c058b373dbd4adbfc48fda4b4e3402ec070499d7cd1e737f3a8b
license     : GPL-2.0+
summary     : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps   :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libgsf-1)
description : |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
setup       : |
    %configure
build       : |
    %make
install     : |
    %make_install
