name       : libgoffice
version    : 0.10.45
release    : 16
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.45.tar.xz : 702ba567e9ec0bbdd9b1a8161cd24648b4868d57a6cb89128f13c125f6f31947
license    : GPL-2.0-or-later
component  : programming.library
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
