name       : libgoffice
version    : 0.10.48
release    : 18
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.48.tar.xz : a439162fa26a0e58117e07b82b37000a7f421088ad379eb1f6a1cdee101ecefc
license    : GPL-2.0-or-later
component  : programming.library
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
