name       : libgoffice
version    : 0.10.55
release    : 27
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.55.tar.xz : 16a221191855a6a6c0d06b1ef8e481cf3f52041a654ec96d35817045ba1a99af
license    : GPL-2.0-or-later
component  : programming.library
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
