name       : libgoffice
version    : 0.10.43
release    : 14
source     :
    - https://download.gnome.org/sources/goffice/0.10/goffice-0.10.43.tar.xz : 550fceefa74622b8fe57dd0b030003e31db50edf7f87068ff5e146365108b64e
license    : GPL-2.0-or-later
component  : programming.library
summary    : The GOffice package contains a library of GLib/GTK document centric objects and utilities.
description: |
    The GOffice package contains a library of GLib/GTK document centric objects and utilities.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libxslt)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
